### ISSUE TITLE
Whitelist buffs not works in Cyrodiil

### ISSUE THREAD

**Issue by ChubarovS** [DakJaniels/LuiExtended#136]
Whitelist buffs not works in Cyrodiil.
Installed the addon to show the buffs I need in pvp, but in Cyrodiil this function does not work (in non-Cyro everything is OK)
I have disabled display all buffs, except those that in the white list*

**Comment by ArtOfShred** [comment]
Sorry for the long delay, what buffs are you trying to whitelist to show in PVP only?

If you're referring to friendly players not properly displaying buffs than that would be an issue with LUI. If you're referring to enemy players, due to API restrictions buffs don't show on enemy players except for Mundus stones.

**Comment by ChubarovS** [comment]
Yes, buffs enemy targets, but they are displayed during duels.

________________________________
От: Shredmaster Reeman <notifications@github.com>
Отправлено: 14 ноября 2019 г. 1:15
Кому: ArtOfShred/LuiExtended <LuiExtended@noreply.github.com>
Копия: ChubarovS <chubarov_s@live.ru>; Author <author@noreply.github.com>
Тема: Re: [ArtOfShred/LuiExtended] Whitelist buffs not works in Cyrodiil (#136)


Sorry for the long delay, what buffs are you trying to whitelist to show in PVP only?

If you're referring to friendly players not properly displaying buffs than that's an error, but enemy targets don't display buffs due to API restrictions (other than the Mundus buff).

**Comment by ChubarovS** [comment]
Buffs on immunity to control*


________________________________
От: Shredmaster Reeman <notifications@github.com>
Отправлено: 14 ноября 2019 г. 1:15
Кому: ArtOfShred/LuiExtended <LuiExtended@noreply.github.com>
Копия: ChubarovS <chubarov_s@live.ru>; Author <author@noreply.github.com>
Тема: Re: [ArtOfShred/LuiExtended] Whitelist buffs not works in Cyrodiil (#136)


Sorry for the long delay, what buffs are you trying to whitelist to show in PVP only?

If you're referring to friendly players not properly displaying buffs than that's an error, but enemy targets don't display buffs due to API restrictions (other than the Mundus buff).

**Comment by ArtOfShred** [comment]
They do display during duels because the API doesn't have any limitations in open world zones, but in Cyrodiil & PVP zones it's not possible currently since Zenimax obfuscates this information from us (outside of Mundus Stone buffs for some reason).

At some point I may use some custom functions to at least show Keep/Emp buffs on players that don't show since that information is available to pull I believe.
