### ISSUE TITLE
ChatAnnouncements 10321 attempt to index a nil value

### ISSUE THREAD

**Issue by korskov** [DakJaniels/LuiExtended#160]
Spurious error during midyear mayhem event.  
Error / stacktrace window can't be removed / closed / etc.

```
user:/AddOns/LuiExtended/modules/ChatAnnouncements/ChatAnnouncements.lua:10321: attempt to index a nil value
stack traceback:
user:/AddOns/LuiExtended/modules/ChatAnnouncements/ChatAnnouncements.lua:10321: in function 'ChatAnnouncements.PrintQueuedMessages'
<Locals> i = 3 </Locals>
```

**Comment by ArtOfShred** [comment]
What's the context for when this error occured / any idea what type of message it might have been? (Loot, Currency, Experience, some kind of system message, etc...)

**Comment by korskov** [comment]
I don't have a slightest idea -- this is never happened before or after this. I thied to reproduce error with other PCs, but no avail. There was nothing special or informative in chat messages either.  
Maybe some network error, or illegal message in a channel.

**Comment by ArtOfShred** [comment]
Okay no worries, now that I take a closer look I see the context isn't necessarily as important to fix the issue.

Chat Announcements uses a printer function - and whenever something happens that should show a message it gets added to the list of messages, and the printer function is turned on with a 50 ms delay to allow other messages to get collected. Then they get filtered by the printer function and displayed.

What appears to have happened here is the 3rd message the printer iterated over (the i = 3 there) wasn't ever set but a 4th one was. So the message index went like (1, 2, 4, 5, etc...) Since I don't check for the message existing before I check for the text and type of the message, it threw an error.

It's possible I made a slight mistake somewhere in a function that gets called seldomly and that's what caused this, but ultimately the solution I should use is to check for the message existing first (which is really how I should have done it in the first place). I'll change this for the next update, which should be coming out within a few days.

Thanks for reporting this! I'll close and comment on this issue once I push and update it on GitHub.

**Comment by ArtOfShred** [comment]
Fixed on development. Will be pushed into the new update soon.
