### ISSUE TITLE
Move default UI element: notifications

### ISSUE THREAD

**Issue by thesimonho** [DakJaniels/LuiExtended#161]
Any plans to allow moving the 'notifications' element of the default UI? (the thing that usually appears in the top right of the screen to indicate zone changes and other bits of information)

Right now the only reason I'm using azurah is to move that 1 element, which feels like a bit wasteful

**Comment by ArtOfShred** [comment]
At some point I do want to add this - and possibly the Compass and Experience Bar as well.

The reason I didn't in this update is because those 3 elements don't like being moved.
- The compass bar likes to snap back to its normal position.
- The xp bar throws errors when its moved.
- Alerts don't seem to want to move by just moving the frame for them.

Thanks for confirming your interest in this feature!

At some point I'll try registering some handlers so they move properly.

**Comment by Tiara-Ra** [comment]
In Bandits Interface almost all elements (default and from custom) possible to move. Mb u can check how he did it.

**Comment by thesimonho** [comment]
yeah both Bandits and Azurah allow you to move most/all of the default UI elements

**Comment by ArtOfShred** [comment]
Alright added this functionality to the GitHub build (and a few other elements as well). I'll try to do an update within a few days.
