### ISSUE TITLE
Highlight important buffs.

### ISSUE THREAD

**Issue by FAR747** [DakJaniels/LuiExtended#173]
**Is your feature request related to a problem? Please describe.**
Add the option of highlighting important buffs like: Major Slayer, Major brutality, etc.

I see it like this. When this buff is applied to a player, the buff icon on the panel becomes larger.

You can also add a whitelist for buffs that will increase in the panel.

**Comment by ArtOfShred** [comment]
I think this is a feature BanditsUI currently has is it not?
The idea is sound but since LUI has stacking buff containers when anchored to the UnitFrames I wouldn't want those containers to get any bigger than they are now, so I just don't think it would work very well with that in mind. Plus I already have the prominent buff containers for important buffs.

I could maybe add a special colored highlight border for important buffs instead?

**Comment by FAR747** [comment]
I think colored frames are a good idea.

**Comment by ArtOfShred** [comment]
Closing this, opened a tracker for a few new features for buffs and debuffs here with this included:
https://github.com/ArtOfShred/LuiExtended/issues/179
