### ISSUE TITLE
Prominent buffs/debuffs

### ISSUE THREAD

**Issue by thesimonho** [DakJaniels/LuiExtended#174]
Under the prominent buffs and debuffs section it says:

`Eligible effects: buffs on player, debuffs on target...`

I'm wondering why you cant also set up the reverse and also include debuffs on player and buffs on target?

In PVP situations, I would want a timer bar to show up if someone has applied purifying light on me (for example), which tells me I need to start playing a bit more defensively. Or if the enemy has activated some ability that gives them an important buff that I need to track (e.g. crystal fragments has procced so I should anticipate the incoming burst)

Maybe have a total of 4 containers that can track these different combinations of player/target buff/debuff?

**Comment by ArtOfShred** [comment]
One issue here (at least for PVP) is that buffs on enemy targets can't be tracked due to the API obfuscating that information from us in PVP areas.

If I were to track prominent debuffs applied onto the player it'd have to be through a different container/filter system. As far as tracking pve enemy buffs I'm less likely to do that as combat alerts should ideally handle notifying you if an enemy boss is enraged, etc.

Adding a container for prominent debuffs on the player is something I've potentially considered doing at some point. I was almost thinking of doing something sort of like the Status Effect tracking in Dark Souls roughly in the center of your UI below your character that has a larger countdown bar and indicator. Still not sure if/when I want to implement this. I've started to lean toward just blacklisting the major/minor buffs/debuffs (added buttons for it recently to make it easier) so that the only debuffs on me are more easily visible, especially in pve where there generally aren't as many debuffs going out.

**Comment by thesimonho** [comment]
Yeah i think debuffs on player would be more important than buffs on target. I'm mostly thinking of this from a PVP perspective. The thing that is missing from basically all status tracking addons is fine grained control of what specific things you want to show/hide

So with your example of black/whitelisting all major or minor debuffs, I think most addons have this feature but in reality its not the entire category of major/minor debuffs that I want to track or hide, it is specific ones that I need to take action on. For example, I want to know if I have maim on me so I know not to go fully offensive, or defile so I know to shield instead of heal. Showing/hiding entire categories (eg all major debuffs) doesnt really help solve the pollution problem because in reality I might only care about a few of the debuffs

**Comment by ArtOfShred** [comment]
Closing this issue, made a tracker for Buff & Debuffs changes here:
https://github.com/ArtOfShred/LuiExtended/issues/179
Still not entirely sure how to implement this but I wanted to consolidate a few things there.
