### ISSUE TITLE
Add "Prominent Buffs"

### ISSUE THREAD

**Issue by psypanda** [DakJaniels/LuiExtended#18]
It would be awesome to have a "Prominent Buffs" window kinda like [Srendarr](http://www.esoui.com/downloads/info655-Srendarr-AuraBuffDebuffTracker.html#info) does, so you can set a user generated list of specific buffs/debuffs to track.

At the moment I am using Srendarr only because of this feature so I have my prominent buffs in a separate window (see [Screenshot](http://prntscr.com/e58jql))

I think it would be a great addition to LUI

**Comment by ArtOfShred** [comment]
Display setup:
* [x] Add containers for prominent (de)buffs (allow tracking for both debuffs & buffs in either container - IE someone wants hurricane to show up with their dots as a debuff for easier tracking)
* [x] Add progress bar for prominent (de)buffs
* [x] Add name option for prominent (de)buffs
* [x] Add at least vertical stacking container display method (it seems most users show prominent buffs in this manner)
* [x] Optional - add horizontal stacking method or tiling structure (IE stack buffs horiz/vert, max length/height = "x" # of buffs)

Dropdown menu options:
* [x] Allow add specific ids.
* [x] Allow add specific names (will show any named effect of a type) - Possibly add buff/debuff filter option on this due to design choice of allowing the player to choose effects to appear in either container. It's likely a player wouldn't want to track both the HoT & Bleed simultaneously from something like Blood Craze for example. So entries would be Name: Buff, Name: Debuff, AbilityId

**Comment by ArtOfShred** [comment]
Implemented!
