### ISSUE TITLE
cp raid frames

### ISSUE THREAD

**Issue by elerave** [DakJaniels/LuiExtended#182]
please make an option to see cp on the raid frames

**Comment by ArtOfShred** [comment]
I don't have any intention of adding any more details to the raid frames at the moment since I want to keep them compact. If I ever overhauled the raid frames at all in the future it might be a consideration, but pretty unlikely for now.

One thing I might consider is adding a mouseover option for Group / Raid Unit Frames that shows you:
Character Name (Account Name) # CP
