### ISSUE TITLE
Long term effects: food buff missing

### ISSUE THREAD

**Issue by thesimonho** [DakJaniels/LuiExtended#183]
This is a very minor issue, but the food buff disappears from the long-term effects list (when using a separate control) when the remaining buff duration is low. Seems to happen when theres less than maybe 2 minutes remaining?

**Comment by thesimonho** [comment]
oh is this because long term effects arent actually a predefined list of effects, but rather defined entirely by duration? because when the food duration runs low I see it in the buffs area of my player frame. would it make sense to keep certain things fixed as "long term" effects so they dont keep switching locations?

**Comment by ArtOfShred** [comment]
Yeah you are correct, it's done simply by buffs that have a duration longer than 2 min. 

I like your idea though. Hmm. I'll look into potentially just making a long term "list." This would also solve another issue that occurs where buffs move from long to short term container and don't update properly which I've been prolonging fixing for far too long.

**Comment by ArtOfShred** [comment]
Alright I adjusted this so that long term effects just stay in their container the whole time.
Now the only potential issue is I might be missing a few effects that last long term. I have to manually flag them to stay in the long term container. Thankfully have a pretty thorough list of effects so shouldn't be much of an issue with anything other than some random quests buffs/etc.

GitHub build updated. Closing this issue, and thanks again for the suggestion this is a time saver!
