### ISSUE TITLE
UI error with game hangs after refining 1+k units of platinum dust

### ISSUE THREAD

**Issue by korskov** [DakJaniels/LuiExtended#191]
after refining around 1+k units of platinum dust, I got this (persistent) UI error window. Also, game performance severely degraded over short time, until it deadhangs.

LUI Ext. v 6.2.2, platform - PC

```
user:/AddOns/LuiExtended/modules/ChatAnnouncements/ChatAnnouncements.lua:3973: operator < is not supported for number < nil
stack traceback:
user:/AddOns/LuiExtended/modules/ChatAnnouncements/ChatAnnouncements.lua:3973: in function 'ChatAnnouncements.ItemPrinter'
user:/AddOns/LuiExtended/modules/ChatAnnouncements/ChatAnnouncements.lua:4193: in function 'ChatAnnouncements.SendDelayedItems'
```

**Comment by ArtOfShred** [comment]
Sorry for the delay in responding to this.

Not entirely sure what causes this as I haven't been able to replicate it. For now I think the best solution will just be to stop the message from displaying if information is missing so it doesn't throw errors. Should be fixed in this manner on the GitHub build.

Thanks for reporting the issue!
