### ISSUE TITLE
Preview Unit Frame Configuration Appearance with mocked up bars

### ISSUE THREAD

**Issue by TakTheExplicable** [DakJaniels/LuiExtended#223]
As a LUIExtended user mainly in a healer role, i would like to be able to preview the configuration of my group and trial bars without being in a group.  

I would like to see 4 unit frames for small group and 12 for trial, with the appearance matching my configuration.  As it is today, I can only view my configuration while in a group, and there usually isn't time to do make adjustments before we begin.  As a healer, a proper config is super important and seeing the way my settings will appear in a real group is important.

In a perfect world, I would like to see the mock-up temporarily in the center of the screen so that I can have the LUIExtended Unit Frames configuration screen and the results without backing out of the configuration screen.  The container would move back to it's configured position once settings are closed.  However, that's a nice to have.

**Comment by TakTheExplicable** [comment]
I see now that i can unlock and move the frame to see results as i configure, so forget the "perfect world" paragraph.

**Comment by ArtOfShred** [comment]
Thanks for the suggestion!
It sounds simple in concept but it would take a lot of time to make a feature like this work (since it would involve creating a bunch of dummy data for fake group units existing). I'll keep this in mind as like a potential future feature since I agree it would be nice for quality of life.

Going to close this for now but adding to #148.
