### ISSUE TITLE
ICE FORTRESS FOR PROMINENT BUFFS

### ISSUE THREAD

**Issue by SaKGEE** [DakJaniels/LuiExtended#95]
ICE FORTRESS FOR PROMINENT BUFFS also blame psypanda :)

**Comment by psypanda** [comment]
There is a setting called "Display Extra Buffs" in
`LuiExtended > Buffs & Debuffs > Position and Display Options` 
![LAM Settings Window](https://i.imgur.com/Z7hOvcn.png)

The problem was that this option was disabled by default. I'll go and change that.
After enabling the setting Ice Fortress has the ID `86130`
This issue can be closed.
